/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

import type { APIRequest, TransportConnectionParams } from '@pipecat-ai/client-js';

export type TransportType = 'daily' | 'smallwebrtc' | 'websocket';
export type AIMode = 'realtime' | 'cascade';
export type RealtimeAIProvider = 'google' | 'openai';
export type AIProvider = RealtimeAIProvider | 'openai-compatible';

export interface AIProfile {
  mode: AIMode;
  provider: AIProvider;
}

export const AVAILABLE_TRANSPORTS: TransportType[] = [
  'smallwebrtc',
];

export const TRANSPORT_LABELS: Record<TransportType, string> = {
  daily: 'Daily',
  smallwebrtc: 'SmallWebRTC',
  websocket: 'WebSocket',
};

export const DEFAULT_TRANSPORT: TransportType = 'smallwebrtc';

const configuredMode = import.meta.env.VITE_DEFAULT_AI_MODE;
const configuredRealtimeProvider = import.meta.env.VITE_DEFAULT_REALTIME_PROVIDER;
const configuredCascadeProvider = import.meta.env.VITE_DEFAULT_CASCADE_VLM_PROVIDER;

export const DEFAULT_REALTIME_PROVIDER: RealtimeAIProvider =
  configuredRealtimeProvider === 'openai' ? 'openai' : 'google';

export const DEFAULT_CASCADE_PROVIDER: AIProvider =
  configuredCascadeProvider === 'google' || configuredCascadeProvider === 'openai'
    ? configuredCascadeProvider
    : 'openai-compatible';

export const DEFAULT_AI_PROFILE: AIProfile = {
  mode: configuredMode === 'cascade' ? 'cascade' : 'realtime',
  provider:
    configuredMode === 'cascade'
      ? DEFAULT_CASCADE_PROVIDER
      : DEFAULT_REALTIME_PROVIDER,
};

const botStartUrl =
  import.meta.env.VITE_BOT_START_URL || 'http://localhost:7870/start';
const botStartPublicApiKey = import.meta.env.VITE_BOT_START_PUBLIC_API_KEY;

const headers = botStartPublicApiKey
  ? new Headers({ Authorization: `Bearer ${botStartPublicApiKey}` })
  : undefined;

/**
 * Append the connection token (if any) to the WebSocket URL returned by the
 * server before the transport connects.
 */
const websocketResponseTransformer = (
  response: TransportConnectionParams
): TransportConnectionParams => {
  const { wsUrl, token } = response as { wsUrl: string; token?: string };
  return {
    wsUrl: token ? `${wsUrl}?token=${encodeURIComponent(token)}` : wsUrl,
  };
};

/**
 * Props passed to `PipecatAppBase` for each transport. WebRTC transports
 * connect in one step via `connectParams`; WebSocket starts the bot first and
 * transforms the response into the WebSocket connection params.
 */
export interface TransportProps {
  connectParams?: APIRequest | TransportConnectionParams;
  startBotParams?: APIRequest;
  startBotResponseTransformer?: (
    response: TransportConnectionParams
  ) => TransportConnectionParams | Promise<TransportConnectionParams>;
}

export const createTransportProps = (
  transport: TransportType,
  profile: AIProfile
): TransportProps => {
  if (transport === 'smallwebrtc') {
    return {
      connectParams: {
        endpoint: botStartUrl,
        headers,
        requestData: {
          createDailyRoom: false,
          enableDefaultIceServers: true,
          transport: 'webrtc',
          body: { mode: profile.mode, provider: profile.provider },
        },
      },
    };
  }

  if (transport === 'daily') {
    return {
      connectParams: {
        endpoint: botStartUrl,
        headers,
        requestData: {
          createDailyRoom: true,
          dailyRoomProperties: { start_video_off: true },
          transport: 'daily',
          body: { mode: profile.mode, provider: profile.provider },
        },
      },
    };
  }

  return {
    startBotParams: {
      endpoint: botStartUrl,
      headers,
      requestData: {
        transport: 'websocket',
        body: { mode: profile.mode, provider: profile.provider },
      },
    },
    startBotResponseTransformer: websocketResponseTransformer,
  };
};
